const app=document.querySelector('#app');const homeBtn=document.querySelector('#homeBtn');let programs={},trouble=[];let size=localStorage.getItem('ip-size');
const liquid={3:'1 taza (250 mL)',6:'1½ tazas (375 mL)',8:'2 tazas (500 mL)'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function boot(){[programs,trouble]=await Promise.all([fetch('data/programs.json').then(r=>r.json()),fetch('data/troubleshooting.json').then(r=>r.json())]);homeBtn.onclick=home;if(!size)setup();else home();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');}
function setup(){app.innerHTML=`<section class="hero"><span class="step">Configuración inicial</span><h1>¿Qué tamaño tenemos?</h1><p>Esto ajusta el mínimo de líquido indicado por el manual.</p></section><div class="stack">${[3,6,8].map(n=>`<button class="choice" data-size="${n}"><strong>${n} Quart</strong>${n===3?'2.8':n===6?'5.7':'7.6'} litros</button>`).join('')}</div>`;document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{size=b.dataset.size;localStorage.setItem('ip-size',size);home()})}
function home(){app.innerHTML=`<section class="hero"><span class="step">Instant Pot Duo V5 · ${size} qt</span><h1>¿Qué quieres hacer?</h1><p>Guía simple para usar la olla sin consultar el manual.</p></section><div class="stack"><button class="primary" id="cook">QUIERO COCINAR</button><button class="secondary" id="zero">GUÍAME DESDE CERO</button><div class="grid"><button class="card" id="progs"><strong>Programas</strong>Tiempos y ajustes</button><button class="card" id="help"><strong>Problemas</strong>Diagnóstico rápido</button><button class="card" id="safe"><strong>Seguridad</strong>Presión y vapor</button><button class="card" id="settings"><strong>Configuración</strong>Cambiar tamaño</button></div></div>`;cook.onclick=chooseProgram;zero.onclick=()=>wizard('Rice','normal',true);progs.onclick=programList;help.onclick=help;safe.onclick=safety;settings.onclick=setup}
function chooseProgram(){app.innerHTML=`<h2>¿Qué vas a cocinar?</h2><div class="stack">${Object.keys(programs).map(k=>`<button class="choice" data-p="${esc(k)}"><strong>${esc(k)}</strong>${esc(programs[k].best[1])}</button>`).join('')}</div>`;document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>chooseSetting(b.dataset.p))}
function chooseSetting(p){const x=programs[p];app.innerHTML=`<span class="step">${esc(p)}</span><h2>Elige el resultado</h2><div class="stack">${['less','normal','more'].map((s,i)=>`<button class="choice" data-s="${s}"><strong>${s[0].toUpperCase()+s.slice(1)} · ${esc(x[s])}</strong>${esc(x.best[i])}</button>`).join('')}</div>`;document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>wizard(p,b.dataset.s,false))}
function wizard(p,setting,fromZero){const x=programs[p],steps=[
['Preparación',fromZero?'Coloca la olla interior dentro de la base. Añade los ingredientes según tu receta.':'Prepara y añade los ingredientes a la olla interior.'],
['Líquido mínimo',`Para tu modelo de ${size} qt, usa al menos ${liquid[size]} de líquido acuoso para cocción a presión, salvo que la receta indique otra cosa.`],
['Cierra la tapa','Alinea la tapa y gírala en sentido horario hasta LOCK. Verifica el aro de sellado y coloca Steam Release en Seal.'],
['Configura la olla',`Presiona ${p}. Selecciona ${setting.toUpperCase()} (${x[setting]}). Presión indicada por el programa: ${x.pressure}. Keep Warm queda activado por defecto.`],
['Espera la presión','La pantalla mostrará On mientras la olla genera presión. Puede tardar hasta unos 30 minutos; alimentos congelados aumentan este tiempo. El temporizador empieza cuando alcanza presión.'],
['Cocción',`El temporizador contará hacia 00:00. Al terminar, la olla emitirá 5 pitidos y finalizará la cocción.`],
['Liberación',releaseText(x.release)],
['Abrir','NO abras hasta que la válvula flotante haya bajado completamente. Después gira la tapa en sentido antihorario y retírala con cuidado, alejando el vapor.']];let i=0;const draw=()=>{let danger=i>=6;app.innerHTML=`<span class="step">Paso ${i+1} de ${steps.length} · ${esc(p)}</span><h2>${esc(steps[i][0])}</h2><div class="notice ${danger?'danger':''}"><div class="big">${esc(steps[i][1])}</div></div>${i===3?`<p><span class="pill">${esc(setting.toUpperCase())}</span><span class="pill">${esc(x[setting])}</span><span class="pill">${esc(x.pressure)}</span></p>`:''}<div class="actions">${i?'<button class="secondary" id="prev">Anterior</button>':''}<button class="primary" id="next">${i===steps.length-1?'Terminar':'Siguiente'}</button></div>`;if(i)prev.onclick=()=>{i--;draw()};next.onclick=()=>{if(i===steps.length-1)home();else{i++;draw()}}};draw()}
function releaseText(r){if(r==='natural')return 'Liberación natural: deja Steam Release en Seal hasta que toda la presión salga por sí sola y la válvula flotante baje. Puede tardar 40 minutos o más.';if(r==='quick-10')return 'Para arroz: deja reposar 10 minutos después de cocinar y luego usa liberación rápida. Mueve Steam Release a Vent manteniendo manos y cara lejos del vapor.';return 'Liberación rápida: mueve Steam Release a Vent y espera a que salga toda la presión. Mantén manos y cara alejadas del vapor.'}
function programList(){app.innerHTML=`<h2>Programas de presión</h2><div class="stack">${Object.entries(programs).map(([k,x])=>`<div class="card"><strong>${esc(k)}</strong><div class="small">Presión: ${esc(x.pressure)}</div><p>Less: ${esc(x.less)} · Normal: ${esc(x.normal)} · More: ${esc(x.more)}</p></div>`).join('')}<div class="card"><strong>Sauté</strong><p>Less 221°F/105°C · Normal 302°F/150°C · More 392°F/200°C. Tiempo predeterminado: 30 min.</p></div><div class="card"><strong>Slow Cook</strong><p>Less ≈ Low · Normal ≈ Medium · More ≈ High. 8 h / 6 h / 4 h.</p></div><div class="card"><strong>Yogurt</strong><p>Less: 24 h; Normal: 8 h (ajustable); More: pasteurización de leche.</p></div><div class="card"><strong>Keep Warm</strong><p>Se activa automáticamente después de la mayoría de programas; hasta 10 horas.</p></div></div>`}
function help(){app.innerHTML=`<h2>Problemas frecuentes</h2><div class="stack">${trouble.map(t=>`<details class="card"><summary><strong>${esc(t.q)}</strong></summary><p>${esc(t.a)}</p></details>`).join('')}</div>`}
function safety(){app.innerHTML=`<h2>Seguridad esencial</h2><div class="stack"><div class="notice danger"><strong>Nunca fuerces la tapa.</strong><p>Antes de abrir, deja salir toda la presión y confirma que la válvula flotante haya bajado.</p></div><div class="card"><strong>Quick Release</strong><p>Usa Vent para liberar rápidamente. Mantén cara y manos lejos del chorro de vapor. El manual lo recomienda para alimentos que tienden a sobrecocerse, como vegetales y mariscos.</p></div><div class="card"><strong>Natural Release</strong><p>Deja el interruptor en Seal hasta que la presión desaparezca. Recomendado por el manual para alimentos que pueden seguir hirviendo, como estofados, chili, pasta, avena, frijoles y granos.</p></div><div class="card"><strong>Líquido</strong><p>${size} qt: mínimo ${liquid[size]} para presión, salvo indicación distinta de la receta. Usa líquidos acuosos como agua, caldo, sopa o jugo.</p></div></div>`}
boot();
